[package]
name = "imagemin_napi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
imagemin = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }

[lints]
workspace = true
