import type { PlaygroundCopy } from "./types";

export const playgroundCopies: Record<"en" | "zh", PlaygroundCopy> = {
  en: {
    addMore: "Add more",
    autoFormat: "Keep input format",
    batchDownload: "Download ZIP",
    clear: "Clear",
    description: "Optimize PNG with imagemin-rs WASM; resize and encode JPEG/WebP with Canvas.",
    download: "Download",
    dropActive: "Release to add images",
    dropHint: "PNG, JPEG, or WebP · up to 50 MB each",
    dropLabel: "Drop images here or choose files",
    empty: "Optimized files will appear here.",
    engine: "Engine",
    engineCanvas: "Canvas",
    engineCanvasWasm: "Canvas + Oxipng WASM",
    engineOriginal: "Original retained",
    engineWasm: "Oxipng WASM",
    failed: "Failed",
    format: "Output format",
    input: "Before",
    jpegFormat: "JPEG",
    keepSmaller: "Keep original when Auto would be larger",
    maxHeight: "Max height",
    maxWidth: "Max width",
    noLimit: "0 keeps the original dimension",
    optimize: "Optimize images",
    optimizing: "Optimizing…",
    output: "After",
    pngFormat: "PNG",
    privacy: "Local only. Files never leave this browser.",
    quality: "Quality",
    queued: "Ready",
    results: "Output queue",
    saved: "saved",
    selected: "selected",
    summary: "Batch summary",
    title: "Browser image workbench",
    webpFormat: "WebP",
  },
  zh: {
    addMore: "继续添加",
    autoFormat: "保持输入格式",
    batchDownload: "下载 ZIP",
    clear: "清空",
    description: "PNG 使用 imagemin-rs WASM 优化；JPEG/WebP 使用 Canvas 调整尺寸与编码。",
    download: "下载",
    dropActive: "松开即可添加图片",
    dropHint: "PNG、JPEG 或 WebP · 单张不超过 50 MB",
    dropLabel: "拖入图片，或点击选择文件",
    empty: "优化后的文件会显示在这里。",
    engine: "处理引擎",
    engineCanvas: "Canvas",
    engineCanvasWasm: "Canvas + Oxipng WASM",
    engineOriginal: "保留原文件",
    engineWasm: "Oxipng WASM",
    failed: "失败",
    format: "输出格式",
    input: "优化前",
    jpegFormat: "JPEG",
    keepSmaller: "自动格式变大时保留原文件",
    maxHeight: "最大高度",
    maxWidth: "最大宽度",
    noLimit: "填 0 保持原始尺寸",
    optimize: "优化图片",
    optimizing: "正在优化…",
    output: "优化后",
    pngFormat: "PNG",
    privacy: "仅在本地处理，文件不会离开浏览器。",
    quality: "质量",
    queued: "待处理",
    results: "输出队列",
    saved: "已节省",
    selected: "已选择",
    summary: "批量汇总",
    title: "浏览器图片工作台",
    webpFormat: "WebP",
  },
};
