/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsNativePluginDescriptor {
  name: string
  optionsJson: string
}

export interface JsOptimizationResult {
  data: Buffer
  format: string
  inputBytes: number
  outputBytes: number
  steps: Array<JsOptimizationStep>
}

export interface JsOptimizationStep {
  plugin: string
  inputBytes: number
  outputBytes: number
  changed: boolean
}

export declare function optimizeNative(input: Buffer, plugins: Array<JsNativePluginDescriptor>): Promise<JsOptimizationResult>
